// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcthS68cs3bYEnZX3KmSmvnsiFexwfVUg',
    appId: '1:291246486950:web:1ba651fef51bed8ba9cb67',
    messagingSenderId: '291246486950',
    projectId: 'mobile-9accd',
    authDomain: 'mobile-9accd.firebaseapp.com',
    storageBucket: 'mobile-9accd.firebasestorage.app',
    measurementId: 'G-LKZGLESR8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_2dhbdGi1KpLaOlN0wrBNXLnvv58OdEA',
    appId: '1:291246486950:android:5a478634c423eaf0a9cb67',
    messagingSenderId: '291246486950',
    projectId: 'mobile-9accd',
    storageBucket: 'mobile-9accd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Rz_JrKZDgz6-cDqgJvUVZtX97-FSKbc',
    appId: '1:291246486950:ios:feb7f44b1083dacaa9cb67',
    messagingSenderId: '291246486950',
    projectId: 'mobile-9accd',
    storageBucket: 'mobile-9accd.firebasestorage.app',
    iosBundleId: 'com.example.tes1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Rz_JrKZDgz6-cDqgJvUVZtX97-FSKbc',
    appId: '1:291246486950:ios:feb7f44b1083dacaa9cb67',
    messagingSenderId: '291246486950',
    projectId: 'mobile-9accd',
    storageBucket: 'mobile-9accd.firebasestorage.app',
    iosBundleId: 'com.example.tes1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcthS68cs3bYEnZX3KmSmvnsiFexwfVUg',
    appId: '1:291246486950:web:c812e7d385817c90a9cb67',
    messagingSenderId: '291246486950',
    projectId: 'mobile-9accd',
    authDomain: 'mobile-9accd.firebaseapp.com',
    storageBucket: 'mobile-9accd.firebasestorage.app',
    measurementId: 'G-1YSLPWVY87',
  );
}
